### PR TITLE
fix: adjust splitwise csv parsing for when a group has multiple currencies

### PR DESCRIPTION
**Pull request by bzhang0**
as title

### CODE REVIEW

**Comment by Pkfire26** [comment]
Leaving a comment

**Comment by bzhang0** [comment]
??? 🤣

**Review by Pkfire26 — COMMENTED** [review]
yes

**Review by ChetanNair — COMMENTED** [review]
LGTM but needs formal proof of correctness! Proof by induction preferably. No proof no approve !

**Comment by Pkfire26** [comment]
> 

I concur

**Comment by bzhang0** [comment]
> LGTM but needs formal proof of correctness! Proof by induction preferably. No proof no approve !

One day....

**Comment by Pkfire26** [comment]
> LGTM but needs formal proof of correctness! Proof by induction preferably. No proof no approve !

I concur

**Review by ChetanNair — APPROVED** [review]
Proof is in the works but is mostly waffle. I'll allow it for now.

**Pull request merged**
